
export const beerActivities = [
    {"activity": "Moagem: Triturar o malte de cevada para expor os amidos.", "category": "AV", "color_code": "Green", "id": "BA001"},
    {"activity": "Mostura: Misturar os grãos moídos com água quente para converter amidos em açúcares fermentáveis.", "category": "AV", "color_code": "Green", "id": "BA002"},
    {"activity": "Lauterização/Clarificação: Separar o líquido doce (mosto) das cascas dos grãos.", "category": "AV", "color_code": "Green", "id": "BA003"},
    {"activity": "Fervura: Ferver o mosto com lúpulo para esterilizar, extrair sabores/aromas do lúpulo e concentrar o mosto.", "category": "AV", "color_code": "Green", "id": "BA004"},
    {"activity": "Whirlpool: Criar um vórtice para decantar sólidos (trub) após a fervura.", "category": "AV", "color_code": "Green", "id": "BA005"},
    {"activity": "Resfriamento do Mosto: Resfriar rapidamente o mosto até a temperatura correta para a inoculação da levedura.", "category": "AV", "color_code": "Green", "id": "BA006"},
    {"activity": "Fermentação: Adicionar levedura ao mosto resfriado para converter açúcares em álcool e CO2.", "category": "AV", "color_code": "Green", "id": "BA007"},
    {"activity": "Maturação/Condicionamento: Permitir que a cerveja envelheça, desenvolva sabores e clarifique.", "category": "AV", "color_code": "Green", "id": "BA008"},
    {"activity": "Carbonatação: Adicionar CO2 à cerveja para a efervescência desejada.", "category": "AV", "color_code": "Green", "id": "BA009"},
    {"activity": "Envase (Encher garrafas/latas/barris): Colocar a cerveja finalizada em recipientes para venda.", "category": "AV", "color_code": "Green", "id": "BA010"},
    {"activity": "Limpeza de Equipamentos (ex: tanques, tubulações): Garantir a sanitização para prevenir contaminação.", "category": "NVA-N", "color_code": "Yellow", "id": "BA011"},
    {"activity": "Sanitização de Equipamentos: Reduzir microrganismos a níveis aceitáveis antes do uso.", "category": "NVA-N", "color_code": "Yellow", "id": "BA012"},
    {"activity": "Controles de Qualidade (ex: leituras de temperatura, densidade, pH): Monitorar parâmetros do processo.", "category": "NVA-N", "color_code": "Yellow", "id": "BA013"},
    {"activity": "Manutenção de Registros: Documentar números de lote, ingredientes e dados do processo para rastreabilidade.", "category": "NVA-N", "color_code": "Yellow", "id": "BA014"},
    {"activity": "Recebimento de Matérias-Primas (ex: malte, lúpulo, levedura): Descarregar e verificar remessas.", "category": "NVA-N", "color_code": "Yellow", "id": "BA015"},
    {"activity": "Armazenamento de Matérias-Primas: Guardar adequadamente os ingredientes antes do uso.", "category": "NVA-N", "color_code": "Yellow", "id": "BA016"},
    {"activity": "Gestão de Estoque: Controlar quantidades de matérias-primas e produtos acabados.", "category": "NVA-N", "color_code": "Yellow", "id": "BA017"},
    {"activity": "Transferência de Mosto/Cerveja entre tanques: Mover o produto por diferentes estágios do processo.", "category": "NVA-N", "color_code": "Yellow", "id": "BA018"},
    {"activity": "Tempo de Setup/Troca: Preparar o equipamento para um novo lote ou tipo de cerveja diferente.", "category": "NVA-N", "color_code": "Yellow", "id": "BA019"},
    {"activity": "Manutenção de Rotina dos Equipamentos: Garantir que a maquinaria esteja operacional.", "category": "NVA-N", "color_code": "Yellow", "id": "BA020"},
    {"activity": "Verificações de Conformidade Regulatória: Garantir a aderência às leis de segurança alimentar e produção de álcool.", "category": "NVA-N", "color_code": "Yellow", "id": "BA021"},
    {"activity": "Espera por materiais/equipamentos: Tempo ocioso devido à falta de insumos ou disponibilidade de máquinas.", "category": "NVA", "color_code": "Red", "id": "BA022"},
    {"activity": "Movimentação excessiva de materiais/pessoal: Transporte ou caminhada desnecessários.", "category": "NVA", "color_code": "Red", "id": "BA023"},
    {"activity": "Retrabalho de um lote devido a erro: Corrigir erros que causaram cerveja fora das especificações.", "category": "NVA", "color_code": "Red", "id": "BA024"},
    {"activity": "Superprodução: Produzir mais cerveja do que a demanda existente.", "category": "NVA", "color_code": "Red", "id": "BA025"},
    {"activity": "Produção de cerveja defeituosa (ex: off-flavors, contaminação) que deve ser descartada.", "category": "NVA", "color_code": "Red", "id": "BA026"},
    {"activity": "Procura por ferramentas ou ingredientes: Tempo perdido devido a um local de trabalho desorganizado.", "category": "NVA", "color_code": "Red", "id": "BA027"},
    {"activity": "Inspeção desnecessária: Verificar mais do que o necessário sem agregar valor.", "category": "NVA", "color_code": "Red", "id": "BA028"},
    {"activity": "Processos de aprovação complexos: Excesso de assinaturas causando atrasos.", "category": "NVA", "color_code": "Red", "id": "BA029"},
    {"activity": "Derramamentos ou vazamentos de ingredientes ou produto.", "category": "NVA", "color_code": "Red", "id": "BA030"},
    {"activity": "Armazenamento de estoque obsoleto (ex: lúpulo velho, levedura vencida).", "category": "NVA", "color_code": "Red", "id": "BA031"},
    {"activity": "Recipientes enchidos incorretamente (abaixo/acima do volume) levando à rejeição.", "category": "NVA", "color_code": "Red", "id": "BA032"},
    {"activity": "Filtragem da cerveja: Remover partículas e leveduras para clarificar e estabilizar a cerveja.", "category": "AV", "color_code": "Green", "id": "BA033"},
    {"activity": "Dry-hopping (adição de lúpulo a frio): Adicionar lúpulo à cerveja fermentada para extrair aromas intensos.", "category": "AV", "color_code": "Green", "id": "BA034"},
    {"activity": "Pasteurização: Aquecer a cerveja para estabilizar microbiologicamente e prolongar a validade.", "category": "AV", "color_code": "Green", "id": "BA035"},
    {"activity": "Blending (mistura de lotes/cervejas): Combinar diferentes cervejas para atingir um perfil de sabor específico.", "category": "AV", "color_code": "Green", "id": "BA036"},
    {"activity": "Calibração de instrumentos (ex: termômetros, densímetros): Garantir a precisão das medições para o controle de qualidade.", "category": "NVA-N", "color_code": "Yellow", "id": "BA037"},
    {"activity": "Tratamento de efluentes/águas residuais: Gerenciar a água utilizada no processo antes do descarte para conformidade ambiental.", "category": "NVA-N", "color_code": "Yellow", "id": "BA038"},
    {"activity": "Verificações de segurança no local de trabalho: Inspeções para garantir um ambiente de trabalho seguro e prevenir acidentes.", "category": "NVA-N", "color_code": "Yellow", "id": "BA039"},
    {"activity": "Gestão de fornecedores: Avaliar e manter relacionamento com fornecedores de matérias-primas para garantir qualidade e pontualidade.", "category": "NVA-N", "color_code": "Yellow", "id": "BA040"},
    {"activity": "Planejamento da produção: Organizar a sequência de lotes e alocação de recursos para otimizar o fluxo.", "category": "NVA-N", "color_code": "Yellow", "id": "BA041"},
    {"activity": "Design e impressão de rótulos/embalagens: Criar e produzir materiais de embalagem para o produto final.", "category": "NVA-N", "color_code": "Yellow", "id": "BA042"},
    {"activity": "Subutilização de habilidades/talentos da equipe: Não aproveitar plenamente as capacidades e conhecimentos dos funcionários.", "category": "NVA", "color_code": "Red", "id": "BA043"},
    {"activity": "Duplicação ou entrada excessiva de dados: Inserir as mesmas informações em múltiplos sistemas ou documentos.", "category": "NVA", "color_code": "Red", "id": "BA044"},
    {"activity": "Aprovações desnecessárias ou em cascata: Processos burocráticos que não agregam valor e atrasam as operações.", "category": "NVA", "color_code": "Red", "id": "BA045"},
    {"activity": "Procura por informações (ex: receitas, procedimentos): Tempo perdido devido à falta de documentação ou organização.", "category": "NVA", "color_code": "Red", "id": "BA046"},
    {"activity": "Equipamento parado por falta de operador: Máquinas disponíveis, mas sem pessoal para operá-las.", "category": "NVA", "color_code": "Red", "id": "BA047"},
    {"activity": "Danos a produtos durante o transporte interno: Cerveja ou ingredientes danificados por manuseio inadequado.", "category": "NVA", "color_code": "Red", "id": "BA048"},
    {"activity": "Manter estoque excessivo de produto acabado: Armazenar mais cerveja do que a demanda imediata, gerando custos desnecessários.", "category": "NVA", "color_code": "Red", "id": "BA049"},
    {"activity": "Reuniões improdutivas: Encontros longos sem objetivos claros ou decisões tomadas.", "category": "NVA", "color_code": "Red", "id": "BA050"},
    {"activity": "Adição de adjuntos/frutas/especiarias: Incorporar ingredientes adicionais para criar perfis de sabor específicos.", "category": "AV", "color_code": "Green", "id": "BA051"},
    {"activity": "Envelhecimento em barril: Armazenar a cerveja em barris de madeira para adicionar complexidade de sabor e aroma.", "category": "AV", "color_code": "Green", "id": "BA052"},
    {"activity": "Recuperação de levedura: Coletar e preparar levedura de um lote para reutilização em futuros lotes.", "category": "AV", "color_code": "Green", "id": "BA053"},
    {"activity": "Engarrafamento/Enlatamento manual: Encher recipientes um por um, sem automação.", "category": "AV", "color_code": "Green", "id": "BA054"},
    {"activity": "Clarificação por centrifugação: Usar força centrífuga para remover sólidos e clarificar a cerveja.", "category": "AV", "color_code": "Green", "id": "BA055"},
    {"activity": "Testes de laboratório (ex: microbiológicos, perfil de sabor): Análises detalhadas para garantir a qualidade e segurança do produto.", "category": "NVA-N", "color_code": "Yellow", "id": "BA056"},
    {"activity": "Treinamento de pessoal: Capacitar funcionários em novas técnicas, equipamentos ou procedimentos de segurança.", "category": "NVA-N", "color_code": "Yellow", "id": "BA057"},
    {"activity": "Auditorias internas/externas: Avaliações sistemáticas para verificar a conformidade com padrões e regulamentos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA058"},
    {"activity": "Gestão de resíduos (ex: bagaço, lúpulo exaurido): Descarte ou reutilização de subprodutos do processo.", "category": "NVA-N", "color_code": "Yellow", "id": "BA059"},
    {"activity": "Processamento de pedidos de clientes: Receber, registrar e preparar pedidos para envio.", "category": "NVA-N", "color_code": "Yellow", "id": "BA060"},
    {"activity": "Emissão de notas fiscais/faturamento: Preparar a documentação financeira para vendas.", "category": "NVA-N", "color_code": "Yellow", "id": "BA061"},
    {"activity": "Manutenção predial: Reparos e conservação das instalações da cervejaria.", "category": "NVA-N", "color_code": "Yellow", "id": "BA062"},
    {"activity": "Gerenciamento de TI: Manutenção de sistemas de computador e redes.", "category": "NVA-N", "color_code": "Yellow", "id": "BA063"},
    {"activity": "Atendimento ao cliente (pré-venda): Fornecer informações sobre produtos e auxiliar na escolha.", "category": "NVA-N", "color_code": "Yellow", "id": "BA064"},
    {"activity": "Limpeza de pisos e áreas comuns: Manter o ambiente geral da cervejaria limpo e organizado.", "category": "NVA-N", "color_code": "Yellow", "id": "BA065"},
    {"activity": "Desperdício de água devido a vazamentos ou uso excessivo: Consumo ineficiente de recursos hídricos.", "category": "NVA", "color_code": "Red", "id": "BA066"},
    {"activity": "Tempo de inatividade da máquina por quebra não planejada: Falha de equipamento resultando em parada da produção.", "category": "NVA", "color_code": "Red", "id": "BA067"},
    {"activity": "Caminhada desnecessária de operadores: Movimento excessivo para buscar ferramentas ou ingredientes.", "category": "NVA", "color_code": "Red", "id": "BA068"},
    {"activity": "Erros de rotulagem/embalagem: Rótulos incorretos ou danificados que exigem retrabalho.", "category": "NVA", "color_code": "Red", "id": "BA069"},
    {"activity": "Superprocessamento do malte: Moer o malte mais fino do que o necessário, gerando mais subprodutos indesejados.", "category": "NVA", "color_code": "Red", "id": "BA070"},
    {"activity": "Aguardar aprovação de compra de insumos: Atraso na aquisição de materiais essenciais.", "category": "NVA", "color_code": "Red", "id": "BA071"},
    {"activity": "Defeitos em embalagens (ex: garrafas quebradas, latas amassadas): Materiais de embalagem que não podem ser usados.", "category": "NVA", "color_code": "Red", "id": "BA072"},
    {"activity": "Excesso de inventário de malte/lúpulo: Armazenamento de grandes quantidades de matérias-primas além da necessidade imediata.", "category": "NVA", "color_code": "Red", "id": "BA073"},
    {"activity": "Comunicação ineficaz entre equipes: Falhas na transmissão de informações que levam a erros ou retrabalho.", "category": "NVA", "color_code": "Red", "id": "BA074"},
    {"activity": "Perda de calor durante a transferência de mosto: Energia desperdiçada devido a isolamento inadequado.", "category": "NVA", "color_code": "Red", "id": "BA075"},
    {"activity": "Tempo de espera para testes de qualidade: Atrasos na liberação de lotes devido à demora nos resultados de laboratório.", "category": "NVA", "color_code": "Red", "id": "BA076"},
    {"activity": "Transporte de mosto/cerveja por longas distâncias desnecessárias dentro da fábrica.", "category": "NVA", "color_code": "Red", "id": "BA077"},
    {"activity": "Reclamações de clientes devido a problemas de qualidade: Necessidade de resolver problemas pós-venda que poderiam ter sido evitados.", "category": "NVA", "color_code": "Red", "id": "BA078"},
    {"activity": "Documentação excessiva e redundante: Preenchimento de formulários desnecessários ou repetidos.", "category": "NVA", "color_code": "Red", "id": "BA079"},
    {"activity": "Falta de padronização nos procedimentos: Cada operador realiza a tarefa de uma forma diferente, levando a inconsistências.", "category": "NVA", "color_code": "Red", "id": "BA080"},
    {"activity": "Subutilização de tanques de fermentação: Tanques vazios por longos períodos devido a planejamento ineficiente.", "category": "NVA", "color_code": "Red", "id": "BA081"},
    {"activity": "Uso de equipamentos superdimensionados para a tarefa: Consumo excessivo de energia e recursos.", "category": "NVA", "color_code": "Red", "id": "BA082"},
    {"activity": "Descarte de levedura viável: Levedura que poderia ser reutilizada, mas é descartada.", "category": "NVA", "color_code": "Red", "id": "BA083"},
    {"activity": "Erros na dosagem de ingredientes: Adicionar mais ou menos do que o necessário, afetando a qualidade ou gerando desperdício.", "category": "NVA", "color_code": "Red", "id": "BA084"},
    {"activity": "Congelamento da cerveja no tanque de maturação: Dano ao produto por falha no controle de temperatura.", "category": "NVA", "color_code": "Red", "id": "BA085"},
    {"activity": "Tempo de espera por manutenção: Equipamento parado aguardando reparo.", "category": "NVA", "color_code": "Red", "id": "BA086"},
    {"activity": "Movimento de pessoas para buscar aprovações físicas: Deslocamento para obter assinaturas em documentos.", "category": "NVA", "color_code": "Red", "id": "BA087"},
    {"activity": "Falha na vedação de barris/garrafas: Vazamento de CO2 ou cerveja após o envase.", "category": "NVA", "color_code": "Red", "id": "BA088"},
    {"activity": "Re-pasteurização de lotes: Repetir o processo de pasteurização devido a falha inicial.", "category": "NVA", "color_code": "Red", "id": "BA089"},
    {"activity": "Preparação de amostras para degustação: Ação de coletar e servir amostras para avaliação sensorial.", "category": "AV", "color_code": "Green", "id": "BA090"},
    {"activity": "Recuperação de CO2: Capturar e purificar CO2 gerado na fermentação para reutilização na carbonatação.", "category": "AV", "color_code": "Green", "id": "BA091"},
    {"activity": "Desenvolvimento de novas receitas: Pesquisa e experimentação para criar novos produtos.", "category": "AV", "color_code": "Green", "id": "BA092"},
    {"activity": "Engarrafamento/Enlatamento automático: Utilizar máquinas para encher e selar recipientes em alta velocidade.", "category": "AV", "color_code": "Green", "id": "BA093"},
    {"activity": "Análise sensorial de cerveja: Avaliação profissional do aroma, sabor e aparência da cerveja.", "category": "AV", "color_code": "Green", "id": "BA094"},
    {"activity": "Gestão de pessoal: Recrutamento, seleção e administração de funcionários.", "category": "NVA-N", "color_code": "Yellow", "id": "BA095"},
    {"activity": "Contabilidade e finanças: Registro de transações financeiras, folha de pagamento e relatórios.", "category": "NVA-N", "color_code": "Yellow", "id": "BA096"},
    {"activity": "Marketing e publicidade: Promoção da marca e dos produtos para atrair clientes.", "category": "NVA-N", "color_code": "Yellow", "id": "BA097"},
    {"activity": "Logística de distribuição: Organização do transporte de produtos acabados para pontos de venda.", "category": "NVA-N", "color_code": "Yellow", "id": "BA098"},
    {"activity": "Pesquisa de mercado: Coleta de dados sobre preferências dos consumidores e tendências do setor.", "category": "NVA-N", "color_code": "Yellow", "id": "BA099"},
    {"activity": "Obtenção de licenças e alvarás: Garantir a permissão legal para operar a cervejaria.", "category": "NVA-N", "color_code": "Yellow", "id": "BA100"},
    {"activity": "Negociação com fornecedores: Discutir termos e condições de compra de matérias-primas.", "category": "NVA-N", "color_code": "Yellow", "id": "BA101"},
    {"activity": "Segurança patrimonial: Proteção das instalações e ativos da cervejaria.", "category": "NVA-N", "color_code": "Yellow", "id": "BA102"},
    {"activity": "Desperdício de energia por equipamentos ociosos: Máquinas ligadas sem estarem em uso.", "category": "NVA", "color_code": "Red", "id": "BA103"},
    {"activity": "Retrabalho de limpeza de tanques: Necessidade de repetir a limpeza devido a falha inicial.", "category": "NVA", "color_code": "Red", "id": "BA104"},
    {"activity": "Tempo de espera por informações de produção: Atrasos causados pela falta de dados em tempo real.", "category": "NVA", "color_code": "Red", "id": "BA105"},
    {"activity": "Movimentação desnecessária de paletes de cerveja acabada no armazém.", "category": "NVA", "color_code": "Red", "id": "BA106"},
    {"activity": "Sobrecarga de trabalho para alguns funcionários, enquanto outros estão ociosos.", "category": "NVA", "color_code": "Red", "id": "BA107"},
    {"activity": "Falha na previsão de demanda: Produzir muito ou pouco em relação ao que será vendido.", "category": "NVA", "color_code": "Red", "id": "BA108"},
    {"activity": "Danos a grãos durante o transporte interno: Perda de matéria-prima por manuseio inadequado.", "category": "NVA", "color_code": "Red", "id": "BA109"},
    {"activity": "Burocracia excessiva para pequenas decisões: Processos lentos para aprovações simples.", "category": "NVA", "color_code": "Red", "id": "BA110"},
    {"activity": "Tempo gasto corrigindo erros de digitação em registros: Retrabalho administrativo.", "category": "NVA", "color_code": "Red", "id": "BA111"},
    {"activity": "Armazenamento desorganizado de ferramentas: Dificuldade em encontrar o que precisa.", "category": "NVA", "color_code": "Red", "id": "BA112"},
    {"activity": "Perda de lúpulo por exposição ao ar/luz: Deterioração da matéria-prima por armazenamento inadequado.", "category": "NVA", "color_code": "Red", "id": "BA113"},
    {"activity": "Desperdício de produtos químicos de limpeza: Uso excessivo ou derramamentos.", "category": "NVA", "color_code": "Red", "id": "BA114"},
    {"activity": "Tempo de espera para o aquecimento da água: Atraso no início do processo de mostura.", "category": "NVA", "color_code": "Red", "id": "BA115"},
    {"activity": "Transferência de mosto para um tanque que não está pronto: Espera desnecessária.", "category": "NVA", "color_code": "Red", "id": "BA116"},
    {"activity": "Degustação de cerveja para controle de qualidade: Provar a cerveja em diferentes estágios para garantir o perfil de sabor.", "category": "AV", "color_code": "Green", "id": "BA117"},
    {"activity": "Envase de barris (kegging): Encher e selar barris para distribuição em chopeiras.", "category": "AV", "color_code": "Green", "id": "BA118"},
    {"activity": "Filtragem de água: Tratar a água para remover impurezas e ajustar o perfil mineral para a cerveja.", "category": "AV", "color_code": "Green", "id": "BA119"},
    {"activity": "Reutilização de garrafas/barris: Processar e sanitizar recipientes retornáveis para novo uso.", "category": "AV", "color_code": "Green", "id": "BA120"},
    {"activity": "Criação de novos produtos (além da cerveja, ex: destilados, refrigerantes): Diversificação da linha de produção.", "category": "AV", "color_code": "Green", "id": "BA121"},
    {"activity": "Gestão de contratos: Elaboração e acompanhamento de acordos com fornecedores e clientes.", "category": "NVA-N", "color_code": "Yellow", "id": "BA122"},
    {"activity": "Gerenciamento de segurança de dados: Proteção de informações confidenciais da empresa.", "category": "NVA-N", "color_code": "Yellow", "id": "BA123"},
    {"activity": "Gestão de licenças de software: Garantir a conformidade legal do uso de programas de computador.", "category": "NVA-N", "color_code": "Yellow", "id": "BA124"},
    {"activity": "Acompanhamento de tendências de mercado: Pesquisa contínua para identificar oportunidades e ameaças.", "category": "NVA-N", "color_code": "Yellow", "id": "BA125"},
    {"activity": "Elaboração de relatórios de desempenho: Análise de métricas de produção e vendas.", "category": "NVA-N", "color_code": "Yellow", "id": "BA126"},
    {"activity": "Participação em feiras e eventos: Representar a cervejaria para networking e promoção.", "category": "NVA-N", "color_code": "Yellow", "id": "BA127"},
    {"activity": "Gestão de reclamações de clientes: Processar e resolver problemas pós-venda.", "category": "NVA-N", "color_code": "Yellow", "id": "BA128"},
    {"activity": "Limpeza de veículos de transporte: Manter a frota limpa e apresentável.", "category": "NVA-N", "color_code": "Yellow", "id": "BA129"},
    {"activity": "Reuniões de equipe para alinhamento: Discussões para coordenar atividades e objetivos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA130"},
    {"activity": "Processamento de devoluções de produtos: Lidar com produtos que retornam do mercado.", "category": "NVA-N", "color_code": "Yellow", "id": "BA131"},
    {"activity": "Tempo de inatividade da linha de envase por congestionamento: Acúmulo de garrafas/latas na esteira.", "category": "NVA", "color_code": "Red", "id": "BA132"},
    {"activity": "Limpeza excessiva de equipamentos já limpos: Gastar tempo e recursos desnecessariamente.", "category": "NVA", "color_code": "Red", "id": "BA133"},
    {"activity": "Espera por decisão gerencial: Processo parado aguardando aprovação de nível superior.", "category": "NVA", "color_code": "Red", "id": "BA134"},
    {"activity": "Transporte de ingredientes em pequenas quantidades várias vezes ao invés de uma única vez.", "category": "NVA", "color_code": "Red", "id": "BA135"},
    {"activity": "Erros na formulação de receitas: Necessidade de ajustes durante o processo que poderiam ter sido evitados.", "category": "NVA", "color_code": "Red", "id": "BA136"},
    {"activity": "Produção de amostras excessivas para testes: Gerar mais amostras do que o necessário, desperdiçando produto.", "category": "NVA", "color_code": "Red", "id": "BA137"},
    {"activity": "Inventário de matérias-primas mal organizado: Dificuldade em localizar itens ou controlar vencimentos.", "category": "NVA", "color_code": "Red", "id": "BA138"},
    {"activity": "Falta de treinamento adequado resultando em erros frequentes: Necessidade de retrabalho ou descarte.", "category": "NVA", "color_code": "Red", "id": "BA139"},
    {"activity": "Interrupções constantes no fluxo de trabalho: Paradas devido a chamadas, e-mails, ou conversas não relacionadas.", "category": "NVA", "color_code": "Red", "id": "BA140"},
    {"activity": "Processos manuais que poderiam ser automatizados: Tarefas repetitivas que consomem tempo e são propensas a erros.", "category": "NVA", "color_code": "Red", "id": "BA141"},
    {"activity": "Deterioração de equipamentos por falta de manutenção preventiva: Quebras que poderiam ser evitadas.", "category": "NVA", "color_code": "Red", "id": "BA142"},
    {"activity": "Desperdício de embalagens secundárias (ex: caixas, divisórias): Danos ou uso incorreto.", "category": "NVA", "color_code": "Red", "id": "BA143"},
    {"activity": "Esperar a temperatura do mosto baixar naturalmente: Falta de sistema de resfriamento eficiente.", "category": "NVA", "color_code": "Red", "id": "BA144"},
    {"activity": "Perda de CO2 durante a transferência de cerveja: Vazamentos ou manuseio inadequado.", "category": "NVA", "color_code": "Red", "id": "BA145"},
    {"activity": "Tempo gasto procurando por peças de reposição: Falta de organização no estoque de manutenção.", "category": "NVA", "color_code": "Red", "id": "BA146"},
    {"activity": "Inspeção visual repetida da mesma garrafa/lata na linha de envase: Excesso de checagem.", "category": "NVA", "color_code": "Red", "id": "BA147"},
    {"activity": "Desperdício de rótulos por desalinhamento na máquina de rotulagem.", "category": "NVA", "color_code": "Red", "id": "BA148"},
    {"activity": "Cerveja presa em tubulações ou mangueiras após a transferência: Perda de produto.", "category": "NVA", "color_code": "Red", "id": "BA149"},
    {"activity": "Armazenamento de produtos acabados em locais inadequados: Exposição a temperaturas extremas ou luz.", "category": "NVA", "color_code": "Red", "id": "BA150"},
    {"activity": "Ajuste do pH do mosto: Correção da acidez para otimizar a atividade enzimática e a fermentação.", "category": "AV", "color_code": "Green", "id": "BA151"},
    {"activity": "Cromatografia de gases/líquidos: Análise de compostos voláteis e não voláteis para perfil de sabor e qualidade.", "category": "AV", "color_code": "Green", "id": "BA152"},
    {"activity": "Propagação de levedura: Multiplicar uma cultura de levedura para obter a quantidade necessária para a fermentação.", "category": "AV", "color_code": "Green", "id": "BA153"},
    {"activity": "Remoção de levedura (floculação/centrifugação): Separar a levedura da cerveja após a fermentação.", "category": "AV", "color_code": "Green", "id": "BA154"},
    {"activity": "Degaseificação da água: Remover oxigênio da água para evitar oxidação na cerveja final.", "category": "AV", "color_code": "Green", "id": "BA155"},
    {"activity": "Desenvolvimento de embalagens inovadoras: Criação de novos designs ou materiais para embalar a cerveja.", "category": "AV", "color_code": "Green", "id": "BA156"},
    {"activity": "Gerenciamento de projetos: Planejamento e execução de iniciativas como expansão da fábrica ou lançamento de produtos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA157"},
    {"activity": "Auditoria de segurança alimentar: Verificação da conformidade com as normas de higiene e segurança na produção.", "category": "NVA-N", "color_code": "Yellow", "id": "BA158"},
    {"activity": "Gestão de contratos de licenciamento: Acordos para uso de marcas ou receitas de terceiros.", "category": "NVA-N", "color_code": "Yellow", "id": "BA159"},
    {"activity": "Limpeza de áreas externas da cervejaria: Manter a fachada e o entorno limpos e convidativos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA160"},
    {"activity": "Gestão de relações públicas: Construir e manter a imagem da marca junto ao público e à mídia.", "category": "NVA-N", "color_code": "Yellow", "id": "BA161"},
    {"activity": "Processamento de pagamentos de fornecedores: Efetuar pagamentos por matérias-primas e serviços.", "category": "NVA-N", "color_code": "Yellow", "id": "BA162"},
    {"activity": "Elaboração de orçamentos: Planejamento financeiro para os próximos períodos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA163"},
    {"activity": "Acompanhamento de legislação trabalhista: Garantir a conformidade com as leis de emprego.", "category": "NVA-N", "color_code": "Yellow", "id": "BA164"},
    {"activity": "Manutenção de bancos de dados de clientes: Organização de informações para marketing e vendas.", "category": "NVA-N", "color_code": "Yellow", "id": "BA165"},
    {"activity": "Tempo de espera por resultados de testes de estabilidade: Atraso na liberação para venda.", "category": "NVA", "color_code": "Red", "id": "BA166"},
    {"activity": "Movimentação de barris vazios para o local de lavagem: Transporte desnecessário se não houver planejamento.", "category": "NVA", "color_code": "Red", "id": "BA167"},
    {"activity": "Retrabalho de lotes por contaminação microbiológica: Processo para tentar salvar cerveja contaminada.", "category": "NVA", "color_code": "Red", "id": "BA168"},
    {"activity": "Superprodução de um estilo de cerveja sazonal: Produzir mais do que a demanda esperada para a estação.", "category": "NVA", "color_code": "Red", "id": "BA169"},
    {"activity": "Produção de amostras para concursos que não geram retorno: Desperdício de produto e tempo.", "category": "NVA", "color_code": "Red", "id": "BA170"},
    {"activity": "Procura por documentação de segurança: Tempo perdido devido a arquivos desorganizados.", "category": "NVA", "color_code": "Red", "id": "BA171"},
    {"activity": "Inspeção de cada garrafa manualmente em uma linha automatizada: Redundância e lentidão.", "category": "NVA", "color_code": "Red", "id": "BA172"},
    {"activity": "Processos de aprovação de marketing excessivamente longos: Atraso no lançamento de campanhas.", "category": "NVA", "color_code": "Red", "id": "BA173"},
    {"activity": "Derramamento de cerveja durante o envase devido a ajuste incorreto da máquina.", "category": "NVA", "color_code": "Red", "id": "BA174"},
    {"activity": "Armazenamento de embalagens obsoletas: Caixas ou rótulos antigos que não serão usados.", "category": "NVA", "color_code": "Red", "id": "BA175"},
    {"activity": "Garrafas/latas com rótulos amassados ou desalinhados: Rejeição ou retrabalho.", "category": "NVA", "color_code": "Red", "id": "BA176"},
    {"activity": "Falta de comunicação sobre mudanças na receita: Erros na produção do lote.", "category": "NVA", "color_code": "Red", "id": "BA177"},
    {"activity": "Tempo de espera para o esvaziamento de tanques: Atraso na limpeza e no próximo lote.", "category": "NVA", "color_code": "Red", "id": "BA178"},
    {"activity": "Movimentação de funcionários para reuniões desnecessárias: Deslocamento e tempo improdutivo.", "category": "NVA", "color_code": "Red", "id": "BA179"},
    {"activity": "Retrabalho de documentos financeiros: Correção de erros em faturas ou relatórios.", "category": "NVA", "color_code": "Red", "id": "BA180"},
    {"activity": "Subutilização de equipamentos de automação: Operar manualmente tarefas que poderiam ser automatizadas.", "category": "NVA", "color_code": "Red", "id": "BA181"},
    {"activity": "Quebra de garrafas durante o transporte para o cliente: Perda de produto final.", "category": "NVA", "color_code": "Red", "id": "BA182"},
    {"activity": "Estoque excessivo de peças de reposição: Capital parado e risco de obsolescência.", "category": "NVA", "color_code": "Red", "id": "BA183"},
    {"activity": "Tempo gasto com a resolução de conflitos internos: Desgaste e improdutividade da equipe.", "category": "NVA", "color_code": "Red", "id": "BA184"},
    {"activity": "Produção de cerveja com sabor inconsistente: Variações que levam à insatisfação do cliente.", "category": "NVA", "color_code": "Red", "id": "BA185"},
    {"activity": "Desperdício de bagaço de malte que poderia ser vendido ou reutilizado: Falta de aproveitamento de subproduto.", "category": "NVA", "color_code": "Red", "id": "BA186"},
    {"activity": "Aguardar a chegada de um técnico externo para um problema simples: Dependência e atraso.", "category": "NVA", "color_code": "Red", "id": "BA187"},
    {"activity": "Processos de feedback de clientes que não geram ações de melhoria: Coleta de dados sem uso prático.", "category": "NVA", "color_code": "Red", "id": "BA188"},
    {"activity": "Uso de mais água do que o necessário na limpeza: Desperdício de recurso.", "category": "NVA", "color_code": "Red", "id": "BA189"},
    {"activity": "Perda de levedura durante a colheita: Ineficiência no processo de recuperação.", "category": "NVA", "color_code": "Red", "id": "BA190"},
    {"activity": "Manutenção corretiva frequente: Reparos de emergência que poderiam ser evitados com preventiva.", "category": "NVA", "color_code": "Red", "id": "BA191"},
    {"activity": "Desperdício de rótulos por mudança de design sem uso do estoque antigo.", "category": "NVA", "color_code": "Red", "id": "BA192"},
    {"activity": "Tempo de espera para o transporte de produto acabado: Caminhões parados aguardando carregamento.", "category": "NVA", "color_code": "Red", "id": "BA193"},
    {"activity": "Reuniões para discutir problemas que já foram resolvidos: Falta de acompanhamento de status.", "category": "NVA", "color_code": "Red", "id": "BA194"},
    {"activity": "Armazenamento de matérias-primas em locais de difícil acesso: Dificuldade na movimentação.", "category": "NVA", "color_code": "Red", "id": "BA195"},
    {"activity": "Desperdício de energia por iluminação desnecessária: Luzes acesas em áreas vazias.", "category": "NVA", "color_code": "Red", "id": "BA196"},
    {"activity": "Atrasos na produção devido a falta de comunicação entre turnos.", "category": "NVA", "color_code": "Red", "id": "BA197"},
    {"activity": "Tempo gasto procurando por informações em múltiplos sistemas não integrados.", "category": "NVA", "color_code": "Red", "id": "BA198"},
    {"activity": "Processo de envase interrompido por falta de garrafas/latas: Espera por insumos.", "category": "NVA", "color_code": "Red", "id": "BA199"},
    {"activity": "Descarte de cerveja que não atende aos padrões de qualidade para venda: Perda total do produto.", "category": "NVA", "color_code": "Red", "id": "BA200"},
    {"activity": "Adição de nutrientes à levedura: Fornecer elementos essenciais para uma fermentação saudável.", "category": "AV", "color_code": "Green", "id": "BA201"},
    {"activity": "Acompanhamento da fermentação (gravidade, temperatura): Monitorar o progresso da conversão de açúcares.", "category": "AV", "color_code": "Green", "id": "BA202"},
    {"activity": "Ajuste da carbonatação para diferentes mercados: Personalizar o nível de efervescência.", "category": "AV", "color_code": "Green", "id": "BA203"},
    {"activity": "Criação de amostras de cerveja para degustação e testes internos.", "category": "AV", "color_code": "Green", "id": "BA204"},
    {"activity": "Elaboração de relatórios de vendas e marketing: Análise do desempenho de mercado.", "category": "NVA-N", "color_code": "Yellow", "id": "BA205"},
    {"activity": "Gerenciamento de redes sociais: Interação com clientes e promoção da marca online.", "category": "NVA-N", "color_code": "Yellow", "id": "BA206"},
    {"activity": "Participação em cursos de aprimoramento profissional: Desenvolvimento de habilidades da equipe.", "category": "NVA-N", "color_code": "Yellow", "id": "BA207"},
    {"activity": "Controle de pragas: Medidas para prevenir infestações na cervejaria.", "category": "NVA-N", "color_code": "Yellow", "id": "BA208"},
    {"activity": "Auditoria de inventário: Contagem física e verificação de estoque.", "category": "NVA-N", "color_code": "Yellow", "id": "BA209"},
    {"activity": "Gerenciamento de contratos de manutenção: Acordos com empresas para serviços em equipamentos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA210"},
    {"activity": "Desperdício de mosto durante a transferência: Perda de líquido devido a vazamentos ou manuseio incorreto.", "category": "NVA", "color_code": "Red", "id": "BA211"},
    {"activity": "Tempo de espera para o sistema de refrigeração atingir a temperatura: Ineficiência do equipamento.", "category": "NVA", "color_code": "Red", "id": "BA212"},
    {"activity": "Movimentação desnecessária de ingredientes do armazém para a área de produção.", "category": "NVA", "color_code": "Red", "id": "BA213"},
    {"activity": "Retrabalho de lotes por erro de densidade/pH: Correção de parâmetros que não estavam dentro do padrão.", "category": "NVA", "color_code": "Red", "id": "BA214"},
    {"activity": "Superprodução de cerveja para eventos que tiveram baixa adesão: Excesso de estoque sem demanda.", "category": "NVA", "color_code": "Red", "id": "BA215"},
    {"activity": "Procura por informações de segurança do produto (FISPQ): Arquivos desorganizados.", "category": "NVA", "color_code": "Red", "id": "BA216"},
    {"activity": "Inspeção de cada barril vazio antes da lavagem: Redundância se a lavadora já tiver sensores.", "category": "NVA", "color_code": "Red", "id": "BA217"},
    {"activity": "Processos de aprovação de despesas que são excessivamente burocráticos.", "category": "NVA", "color_code": "Red", "id": "BA218"},
    {"activity": "Derramamento de lúpulo durante a adição: Perda de matéria-prima cara.", "category": "NVA", "color_code": "Red", "id": "BA219"},
    {"activity": "Armazenamento de equipamentos obsoletos ou quebrados que não serão consertados.", "category": "NVA", "color_code": "Red", "id": "BA220"},
    {"activity": "Garrafas/latas com volume incorreto: Rejeição ou retrabalho na linha de envase.", "category": "NVA", "color_code": "Red", "id": "BA221"},
    {"activity": "Falta de comunicação sobre a disponibilidade de tanques: Atrasos na programação.", "category": "NVA", "color_code": "Red", "id": "BA222"},
    {"activity": "Tempo de espera para a chegada de ingredientes críticos: Atraso na produção.", "category": "NVA", "color_code": "Red", "id": "BA223"},
    {"activity": "Movimentação excessiva de pessoas entre diferentes setores sem necessidade.", "category": "NVA", "color_code": "Red", "id": "BA224"},
    {"activity": "Retrabalho de relatórios de produção: Correção de dados incorretos.", "category": "NVA", "color_code": "Red", "id": "BA225"},
    {"activity": "Subutilização de capacidade de tanques: Encher tanques grandes com pequenos volumes.", "category": "NVA", "color_code": "Red", "id": "BA226"},
    {"activity": "Danos a barris durante o carregamento/descarregamento: Necessidade de reparo ou descarte.", "category": "NVA", "color_code": "Red", "id": "BA227"},
    {"activity": "Estoque excessivo de produtos de limpeza: Capital parado e risco de vencimento.", "category": "NVA", "color_code": "Red", "id": "BA228"},
    {"activity": "Tempo gasto com fofocas ou conversas não relacionadas ao trabalho.", "category": "NVA", "color_code": "Red", "id": "BA229"},
    {"activity": "Produção de cerveja com características sensoriais indesejadas: Perfil de sabor fora do padrão.", "category": "NVA", "color_code": "Red", "id": "BA230"},
    {"activity": "Desperdício de malte moído por exposição à umidade: Perda de qualidade da matéria-prima.", "category": "NVA", "color_code": "Red", "id": "BA231"},
    {"activity": "Aguardar a liberação de um lote por um único responsável: Gargalo no processo.", "category": "NVA", "color_code": "Red", "id": "BA232"},
    {"activity": "Processos de feedback de fornecedores que não são utilizados para melhoria.", "category": "NVA", "color_code": "Red", "id": "BA233"},
    {"activity": "Uso de mais vapor do que o necessário na fervura: Desperdício de energia.", "category": "NVA", "color_code": "Red", "id": "BA234"},
    {"activity": "Perda de cerveja durante a filtragem: Vazamentos ou retenção excessiva no filtro.", "category": "NVA", "color_code": "Red", "id": "BA235"},
    {"activity": "Manutenção preventiva agendada em horário de pico de produção: Interrupção desnecessária.", "category": "NVA", "color_code": "Red", "id": "BA236"},
    {"activity": "Desperdício de etiquetas por erro de impressão ou corte.", "category": "NVA", "color_code": "Red", "id": "BA237"},
    {"activity": "Tempo de espera para o descarregamento de matérias-primas: Caminhões parados na fila.", "category": "NVA", "color_code": "Red", "id": "BA238"},
    {"activity": "Reuniões sem pauta definida ou objetivos claros: Improdutividade.", "category": "NVA", "color_code": "Red", "id": "BA239"},
    {"activity": "Armazenamento de produtos acabados em excesso no corredor: Bloqueio de passagem.", "category": "NVA", "color_code": "Red", "id": "BA240"},
    {"activity": "Desperdício de energia por portas de câmaras frias abertas por muito tempo.", "category": "NVA", "color_code": "Red", "id": "BA241"},
    {"activity": "Atrasos na produção devido a falhas de comunicação entre departamentos.", "category": "NVA", "color_code": "Red", "id": "BA242"},
    {"activity": "Tempo gasto preenchendo formulários em papel que poderiam ser digitais.", "category": "NVA", "color_code": "Red", "id": "BA243"},
    {"activity": "Processo de carbonatação que exige múltiplos ajustes: Ineficiência.", "category": "NVA", "color_code": "Red", "id": "BA244"},
    {"activity": "Descarte de cerveja por oxidação prematura: Falha no controle de oxigênio.", "category": "NVA", "color_code": "Red", "id": "BA245"},
    {"activity": "Re-moagem de malte por moagem inicial inadequada: Retrabalho.", "category": "NVA", "color_code": "Red", "id": "BA246"},
    {"activity": "Uso de mangueiras muito longas para transferências: Aumento da perda de produto e tempo de limpeza.", "category": "NVA", "color_code": "Red", "id": "BA247"},
    {"activity": "Tempo de espera por aprovação de design de rótulo: Atraso no envase.", "category": "NVA", "color_code": "Red", "id": "BA248"},
    {"activity": "Movimentação de barris cheios desnecessariamente antes do carregamento.", "category": "NVA", "color_code": "Red", "id": "BA249"},
    {"activity": "Produção de espuma excessiva durante o envase: Perda de produto e tempo.", "category": "NVA", "color_code": "Red", "id": "BA250"},
    {"activity": "Ajuste de temperatura de fermentação: Controlar a temperatura para guiar o perfil de sabor da levedura.", "category": "AV", "color_code": "Green", "id": "BA251"},
    {"activity": "Recuperação de calor do mosto: Utilizar o calor do mosto resfriado para aquecer a água de mostura.", "category": "AV", "color_code": "Green", "id": "BA252"},
    {"activity": "Testes de estabilidade de prateleira: Simular o envelhecimento para prever a validade da cerveja.", "category": "AV", "color_code": "Green", "id": "BA253"},
    {"activity": "Envase de cervejas especiais (ex: com frutas, envelhecidas em barril): Processos específicos para produtos diferenciados.", "category": "AV", "color_code": "Green", "id": "BA254"},
    {"activity": "Criação de conteúdo para mídias sociais: Produzir textos, fotos e vídeos para engajamento online.", "category": "AV", "color_code": "Green", "id": "BA255"},
    {"activity": "Gestão de projetos de sustentabilidade: Implementar iniciativas para reduzir o impacto ambiental.", "category": "NVA-N", "color_code": "Yellow", "id": "BA256"},
    {"activity": "Elaboração de planos de contingência: Preparação para lidar com emergências ou falhas no processo.", "category": "NVA-N", "color_code": "Yellow", "id": "BA257"},
    {"activity": "Gestão de contratos com distribuidoras: Acordos para a venda e entrega de produtos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA258"},
    {"activity": "Pesquisa e desenvolvimento de novos ingredientes: Explorar alternativas para melhorar produtos ou processos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA259"},
    {"activity": "Gestão de propriedade intelectual: Registro de marcas e patentes para proteger a empresa.", "category": "NVA-N", "color_code": "Yellow", "id": "BA260"},
    {"activity": "Organização de eventos de degustação: Promover a cerveja diretamente ao público.", "category": "NVA-N", "color_code": "Yellow", "id": "BA261"},
    {"activity": "Auditoria de segurança de dados: Verificação da proteção de informações contra acessos não autorizados.", "category": "NVA-N", "color_code": "Yellow", "id": "BA262"},
    {"activity": "Manutenção do sistema de tratamento de água: Garantir a qualidade da água para a produção.", "category": "NVA-N", "color_code": "Yellow", "id": "BA263"},
    {"activity": "Revisão de procedimentos operacionais padrão (POPs): Atualizar e otimizar as instruções de trabalho.", "category": "NVA-N", "color_code": "Yellow", "id": "BA264"},
    {"activity": "Análise de custo-benefício de novos investimentos: Avaliar a viabilidade de aquisição de equipamentos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA265"},
    {"activity": "Espera por aprovação de design de embalagem: Atraso na produção de materiais de envase.", "category": "NVA", "color_code": "Red", "id": "BA266"},
    {"activity": "Movimentação excessiva de paletes vazios no armazém: Desorganização.", "category": "NVA", "color_code": "Red", "id": "BA267"},
    {"activity": "Retrabalho de rótulos por erro de impressão da gráfica: Necessidade de reimpressão.", "category": "NVA", "color_code": "Red", "id": "BA268"},
    {"activity": "Superprodução de rótulos/embalagens: Excesso de material que pode ficar obsoleto.", "category": "NVA", "color_code": "Red", "id": "BA269"},
    {"activity": "Produção de cerveja com teor alcoólico fora das especificações: Erro na formulação.", "category": "NVA", "color_code": "Red", "id": "BA270"},
    {"activity": "Procura por registros de manutenção de equipamentos: Falta de organização de documentos.", "category": "NVA", "color_code": "Red", "id": "BA271"},
    {"activity": "Inspeção manual de cada garrafa para verificar a tampa: Redundância se houver sensor.", "category": "NVA", "color_code": "Red", "id": "BA272"},
    {"activity": "Processos de aprovação de viagens de negócios que são excessivamente complexos.", "category": "NVA", "color_code": "Red", "id": "BA273"},
    {"activity": "Derramamento de insumos durante a pesagem: Perda de matéria-prima.", "category": "NVA", "color_code": "Red", "id": "BA274"},
    {"activity": "Armazenamento de ferramentas em locais não designados: Desorganização e perda de tempo.", "category": "NVA", "color_code": "Red", "id": "BA275"},
    {"activity": "Engarrafamento/enlatamento com defeitos na vedação: Vazamento de produto.", "category": "NVA", "color_code": "Red", "id": "BA276"},
    {"activity": "Falta de comunicação sobre a necessidade de manutenção: Quebra inesperada de equipamento.", "category": "NVA", "color_code": "Red", "id": "BA277"},
    {"activity": "Tempo de espera para o carregamento de caminhões: Atraso na logística.", "category": "NVA", "color_code": "Red", "id": "BA278"},
    {"activity": "Movimentação excessiva de documentos físicos entre departamentos.", "category": "NVA", "color_code": "Red", "id": "BA279"},
    {"activity": "Retrabalho de planejamento de produção: Ajustes constantes devido a erros de previsão.", "category": "NVA", "color_code": "Red", "id": "BA280"},
    {"activity": "Subutilização de espaço de armazenamento: Armazém mal otimizado.", "category": "NVA", "color_code": "Red", "id": "BA281"},
    {"activity": "Danos a equipamentos por uso incorreto: Necessidade de reparo ou substituição.", "category": "NVA", "color_code": "Red", "id": "BA282"},
    {"activity": "Estoque excessivo de peças de reposição que nunca são usadas: Capital parado.", "category": "NVA", "color_code": "Red", "id": "BA283"},
    {"activity": "Tempo gasto com a resolução de problemas de TI que poderiam ser evitados com manutenção preventiva.", "category": "NVA", "color_code": "Red", "id": "BA284"},
    {"activity": "Produção de cerveja com cor fora do padrão: Erro na seleção de malte ou processo.", "category": "NVA", "color_code": "Red", "id": "BA285"},
    {"activity": "Desperdício de água por torneiras abertas desnecessariamente.", "category": "NVA", "color_code": "Red", "id": "BA286"},
    {"activity": "Aguardar a aprovação de um pedido de compra de baixo valor: Burocracia excessiva.", "category": "NVA", "color_code": "Red", "id": "BA287"},
    {"activity": "Processos de recrutamento e seleção ineficientes: Contratação de pessoal inadequado.", "category": "NVA", "color_code": "Red", "id": "BA288"},
    {"activity": "Uso de mais lúpulo do que o necessário para atingir o amargor desejado: Desperdício.", "category": "NVA", "color_code": "Red", "id": "BA289"},
    {"activity": "Perda de cerveja por falha no sistema de CO2: Vazamentos ou pressão inadequada.", "category": "NVA", "color_code": "Red", "id": "BA290"},
    {"activity": "Manutenção corretiva de emergência: Reparo urgente que interrompe a produção.", "category": "NVA", "color_code": "Red", "id": "BA291"},
    {"activity": "Desperdício de embalagens por danos durante o transporte do fornecedor.", "category": "NVA", "color_code": "Red", "id": "BA292"},
    {"activity": "Tempo de espera para o início da mostura devido a atraso na moagem.", "category": "NVA", "color_code": "Red", "id": "BA293"},
    {"activity": "Reuniões para discutir problemas que já foram escalados para outra equipe: Duplicação de esforços.", "category": "NVA", "color_code": "Red", "id": "BA294"},
    {"activity": "Armazenamento de produtos acabados em locais de difícil acesso para expedição.", "category": "NVA", "color_code": "Red", "id": "BA295"},
    {"activity": "Desperdício de energia por sistemas de aquecimento/refrigeração ineficientes.", "category": "NVA", "color_code": "Red", "id": "BA296"},
    {"activity": "Atrasos na produção devido a falta de treinamento do operador.", "category": "NVA", "color_code": "Red", "id": "BA297"},
    {"activity": "Tempo gasto com a entrada manual de dados que poderiam ser importados automaticamente.", "category": "NVA", "color_code": "Red", "id": "BA298"},
    {"activity": "Processo de lavagem de barris que exige múltiplos ciclos: Ineficiência.", "category": "NVA", "color_code": "Red", "id": "BA299"},
    {"activity": "Descarte de cerveja por sabor metálico: Contaminação por equipamento corroído.", "category": "NVA", "color_code": "Red", "id": "BA300"},
    {"activity": "Monitoramento da gravidade final: Verificar o teor de açúcares residuais após a fermentação.", "category": "AV", "color_code": "Green", "id": "BA301"},
    {"activity": "Acompanhamento da temperatura da câmara fria: Garantir a conservação adequada da cerveja.", "category": "AV", "color_code": "Green", "id": "BA302"},
    {"activity": "Preparação de pedidos personalizados: Montar kits ou embalagens especiais para clientes.", "category": "AV", "color_code": "Green", "id": "BA303"},
    {"activity": "Criação de novos sabores de cerveja: Experimentação com ingredientes e processos para inovar.", "category": "AV", "color_code": "Green", "id": "BA304"},
    {"activity": "Desenvolvimento de programas de fidelidade para clientes: Incentivar compras repetidas.", "category": "AV", "color_code": "Green", "id": "BA305"},
    {"activity": "Gestão de segurança alimentar (HACCP): Implementar e monitorar um sistema de controle de perigos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA306"},
    {"activity": "Elaboração de planos de marketing: Definir estratégias para promover a cerveja.", "category": "NVA-N", "color_code": "Yellow", "id": "BA307"},
    {"activity": "Gestão de parcerias com bares e restaurantes: Acordos para distribuição e promoção.", "category": "NVA-N", "color_code": "Yellow", "id": "BA308"},
    {"activity": "Pesquisa e desenvolvimento de embalagens sustentáveis: Buscar alternativas ecologicamente corretas.", "category": "NVA-N", "color_code": "Yellow", "id": "BA309"},
    {"activity": "Gestão de licenças de importação/exportação: Documentação para comércio internacional.", "category": "NVA-N", "color_code": "Yellow", "id": "BA310"},
    {"activity": "Auditoria de conformidade ambiental: Verificação de leis e normas de proteção ambiental.", "category": "NVA-N", "color_code": "Yellow", "id": "BA311"},
    {"activity": "Manutenção de sistemas de ventilação: Garantir a qualidade do ar no ambiente de trabalho.", "category": "NVA-N", "color_code": "Yellow", "id": "BA312"},
    {"activity": "Revisão de contratos com distribuidores: Avaliar e renegociar termos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA313"},
    {"activity": "Análise de mercado para novos produtos: Avaliar a viabilidade de lançamentos.", "category": "NVA-N", "color_code": "Yellow", "id": "BA314"},
    {"activity": "Gerenciamento de reputação online: Monitorar e responder a comentários e avaliações na internet.", "category": "NVA-N", "color_code": "Yellow", "id": "BA315"},
    {"activity": "Espera por laudos de laboratório externos: Atraso na liberação de lotes.", "category": "NVA", "color_code": "Red", "id": "BA316"},
    {"activity": "Movimentação desnecessária de resíduos para descarte: Otimização da rota.", "category": "NVA", "color_code": "Red", "id": "BA317"},
    {"activity": "Retrabalho de relatórios de vendas: Correção de dados imprecisos.", "category": "NVA", "color_code": "Red", "id": "BA318"},
    {"activity": "Superprodução de cerveja para promoções que não geram aumento de vendas.", "category": "NVA", "color_code": "Red", "id": "BA319"},
    {"activity": "Produção de cerveja com amargor fora do padrão: Erro na adição de lúpulo.", "category": "NVA", "color_code": "Red", "id": "BA320"},
    {"activity": "Procura por manuais de equipamentos: Falta de organização de documentação técnica.", "category": "NVA", "color_code": "Red", "id": "BA321"},
    {"activity": "Inspeção de cada garrafa para verificar a data de validade: Redundância se a máquina já tiver sensor.", "category": "NVA", "color_code": "Red", "id": "BA322"},
    {"activity": "Processos de aprovação de marketing que exigem muitas revisões: Atraso na campanha.", "category": "NVA", "color_code": "Red", "id": "BA323"},
    {"activity": "Derramamento de cerveja durante o transporte externo: Perda de produto final.", "category": "NVA", "color_code": "Red", "id": "BA324"},
    {"activity": "Armazenamento de embalagens com defeitos de fabricação: Ocupa espaço e não pode ser usada.", "category": "NVA", "color_code": "Red", "id": "BA325"},
    {"activity": "Garrafas/latas com rótulos rasgados ou sujos: Rejeição ou retrabalho.", "category": "NVA", "color_code": "Red", "id": "BA326"},
    {"activity": "Falta de comunicação entre a equipe de vendas e produção: Desalinhamento de estoque.", "category": "NVA", "color_code": "Red", "id": "BA327"},
    {"activity": "Tempo de espera para o carregamento de bagaço: Atraso no descarte de subproduto.", "category": "NVA", "color_code": "Red", "id": "BA328"},
    {"activity": "Movimentação excessiva de pessoal para buscar café/água: Falta de pontos de hidratação.", "category": "NVA", "color_code": "Red", "id": "BA329"},
    {"activity": "Retrabalho de planos de vendas: Ajustes constantes devido a previsões imprecisas.", "category": "NVA", "color_code": "Red", "id": "BA330"},
    {"activity": "Subutilização de talentos da equipe de vendas: Não aproveitar o potencial dos vendedores.", "category": "NVA", "color_code": "Red", "id": "BA331"},
    {"activity": "Danos a veículos de transporte por falta de manutenção: Custos de reparo e tempo de inatividade.", "category": "NVA", "color_code": "Red", "id": "BA332"},
    {"activity": "Estoque excessivo de material de escritório: Capital parado.", "category": "NVA", "color_code": "Red", "id": "BA333"},
    {"activity": "Tempo gasto com a resolução de problemas de conectividade de rede: Interrupção das operações.", "category": "NVA", "color_code": "Red", "id": "BA334"},
    {"activity": "Produção de cerveja com aroma indesejado: Erro na seleção de lúpulo ou levedura.", "category": "NVA", "color_code": "Red", "id": "BA335"},
    {"activity": "Desperdício de produtos químicos de sanitização: Uso excessivo ou aplicação incorreta.", "category": "NVA", "color_code": "Red", "id": "BA336"},
    {"activity": "Aguardar a aprovação de um plano de marketing: Atraso no lançamento de campanhas.", "category": "NVA", "color_code": "Red", "id": "BA337"},
    {"activity": "Processos de contratação longos e burocráticos: Dificuldade em preencher vagas rapidamente.", "category": "NVA", "color_code": "Red", "id": "BA338"},
    {"activity": "Uso de mais malte do que o necessário para atingir a densidade desejada: Desperdício.", "category": "NVA", "color_code": "Red", "id": "BA339"},
    {"activity": "Perda de cerveja por falha no controle de temperatura de maturação: Dano ao produto.", "category": "NVA", "color_code": "Red", "id": "BA340"},
    {"activity": "Manutenção preventiva de equipamentos que não são críticos: Desvio de recursos.", "category": "NVA", "color_code": "Red", "id": "BA341"},
    {"activity": "Desperdício de embalagens por erros de manuseio na linha de envase.", "category": "NVA", "color_code": "Red", "id": "BA342"},
    {"activity": "Tempo de espera para o reabastecimento de insumos na linha de produção.", "category": "NVA", "color_code": "Red", "id": "BA343"},
    {"activity": "Reuniões para discutir problemas que poderiam ser resolvidos por e-mail ou chat.", "category": "NVA", "color_code": "Red", "id": "BA344"},
    {"activity": "Armazenamento de ingredientes em locais com variação de temperatura: Deterioração.", "category": "NVA", "color_code": "Red", "id": "BA345"},
    {"activity": "Desperdício de energia por sistemas de iluminação antigos e ineficientes.", "category": "NVA", "color_code": "Red", "id": "BA346"},
    {"activity": "Atrasos na produção devido a problemas de qualidade na matéria-prima: Necessidade de substituição.", "category": "NVA", "color_code": "Red", "id": "BA347"},
    {"activity": "Tempo gasto com a busca de informações em arquivos físicos desorganizados.", "category": "NVA", "color_code": "Red", "id": "BA348"},
    {"activity": "Processo de limpeza de garrafas que exige múltiplos enxágues: Ineficiência.", "category": "NVA", "color_code": "Red", "id": "BA349"},
    {"activity": "Descarte de cerveja por sabor de papelão/oxidado: Exposição excessiva ao oxigênio.", "category": "NVA", "color_code": "Red", "id": "BA350"},
    {"activity": "Acompanhamento da pressão nos tanques de fermentação: Monitorar a produção de CO2.", "category": "AV", "color_code": "Green", "id": "BA351"},
    {"activity": "Preparo de soluções de limpeza/sanitização: Diluir e misturar produtos para uso.", "category": "NVA-N", "color_code": "Yellow", "id": "BA352"},
    {"activity": "Inspeção de qualidade de matérias-primas na chegada: Verificar conformidade com especificações.", "category": "NVA-N", "color_code": "Yellow", "id": "BA353"},
    {"activity": "Gerenciamento de redes de computadores da cervejaria: Manter a infraestrutura de TI.", "category": "NVA-N", "color_code": "Yellow", "id": "BA354"},
    {"activity": "Conferência de estoque no almoxarifado: Contagem e organização de materiais.", "category": "NVA-N", "color_code": "Yellow", "id": "BA355"},
    {"activity": "Preenchimento de formulários de segurança do trabalho: Documentação de conformidade.", "category": "NVA-N", "color_code": "Yellow", "id": "BA356"},
    {"activity": "Tempo de espera por caminhões de entrega: Atraso na expedição do produto.", "category": "NVA", "color_code": "Red", "id": "BA357"},
    {"activity": "Movimentação excessiva de cerveja acabada para o armazém e depois para expedição.", "category": "NVA", "color_code": "Red", "id": "BA358"},
    {"activity": "Retrabalho de ordens de produção: Correção de erros na programação.", "category": "NVA", "color_code": "Red", "id": "BA359"},
    {"activity": "Superprodução de cerveja para atender a um pico de demanda irreal: Excesso de estoque.", "category": "NVA", "color_code": "Red", "id": "BA360"},
    {"activity": "Produção de cerveja com baixo rendimento de extração: Ineficiência na mostura.", "category": "NVA", "color_code": "Red", "id": "BA361"},
    {"activity": "Procura por informações de contato de fornecedores: Lista desatualizada ou desorganizada.", "category": "NVA", "color_code": "Red", "id": "BA362"},
    {"activity": "Inspeção desnecessária de equipamentos após cada lote: Excesso de verificação.", "category": "NVA", "color_code": "Red", "id": "BA363"},
    {"activity": "Processos de aprovação de despesas que são excessivamente demorados.", "category": "NVA", "color_code": "Red", "id": "BA364"},
    {"activity": "Derramamento de água quente durante a limpeza: Desperdício e risco de segurança.", "category": "NVA", "color_code": "Red", "id": "BA365"},
    {"activity": "Armazenamento de lúpulo em embalagens danificadas: Perda de aroma e qualidade.", "category": "NVA", "color_code": "Red", "id": "BA366"},
    {"activity": "Garrafas/latas com tampas/lacres mal vedados: Vazamento ou perda de carbonatação.", "category": "NVA", "color_code": "Red", "id": "BA367"},
    {"activity": "Falta de comunicação sobre a qualidade da matéria-prima: Uso de insumos inadequados.", "category": "NVA", "color_code": "Red", "id": "BA368"},
    {"activity": "Tempo de espera para o esvaziamento de silos de malte: Atraso na moagem.", "category": "NVA", "color_code": "Red", "id": "BA369"},
    {"activity": "Movimentação excessiva de caixas de cerveja no armazém: Desorganização ou layout ineficiente.", "category": "NVA", "color_code": "Red", "id": "BA370"},
    {"activity": "Retrabalho de etiquetas de paletes: Correção de informações incorretas.", "category": "NVA", "color_code": "Red", "id": "BA371"},
    {"activity": "Subutilização de veículos de transporte: Caminhões rodando com carga parcial.", "category": "NVA", "color_code": "Red", "id": "BA372"},
    {"activity": "Danos a cerveja durante o transporte para eventos: Perda de produto.", "category": "NVA", "color_code": "Red", "id": "BA373"},
    {"activity": "Estoque excessivo de garrafas/latas vazias: Capital parado e espaço ocupado.", "category": "NVA", "color_code": "Red", "id": "BA374"},
    {"activity": "Tempo gasto com a resolução de conflitos com fornecedores: Desgaste e atrasos.", "category": "NVA", "color_code": "Red", "id": "BA375"},
    {"activity": "Produção de cerveja com turbidez excessiva: Falha na clarificação.", "category": "NVA", "color_code": "Red", "id": "BA376"},
    {"activity": "Desperdício de malte por derramamento durante a moagem.", "category": "NVA", "color_code": "Red", "id": "BA377"},
    {"activity": "Aguardar a decisão sobre o descarte de um lote defeituoso: Atraso na liberação de tanques.", "category": "NVA", "color_code": "Red", "id": "BA378"},
    {"activity": "Processos de aprovação de férias que são excessivamente burocráticos: Dificuldade na gestão de pessoal.", "category": "NVA", "color_code": "Red", "id": "BA379"},
    {"activity": "Uso de mais água do que o necessário no resfriamento do mosto: Desperdício.", "category": "NVA", "color_code": "Red", "id": "BA380"},
    {"activity": "Perda de cerveja por falha no sistema de filtração: Entupimento ou vazamento.", "category": "NVA", "color_code": "Red", "id": "BA381"},
    {"activity": "Manutenção corretiva de última hora: Reparos urgentes que poderiam ser agendados.", "category": "NVA", "color_code": "Red", "id": "BA382"},
    {"activity": "Desperdício de papel por impressão de documentos desnecessários.", "category": "NVA", "color_code": "Red", "id": "BA383"},
    {"activity": "Tempo de espera para o início da fervura devido a aquecimento lento.", "category": "NVA", "color_code": "Red", "id": "BA384"},
    {"activity": "Reuniões para discutir problemas que já foram documentados e não exigem nova discussão.", "category": "NVA", "color_code": "Red", "id": "BA385"},
    {"activity": "Armazenamento de produtos acabados em excesso em áreas de trânsito: Obstrução.", "category": "NVA", "color_code": "Red", "id": "BA386"},
    {"activity": "Desperdício de energia por máquinas operando sem carga: Consumo ocioso.", "category": "NVA", "color_code": "Red", "id": "BA387"},
    {"activity": "Atrasos na produção devido a problemas de qualidade da água: Necessidade de tratamento adicional.", "category": "NVA", "color_code": "Red", "id": "BA388"},
    {"activity": "Tempo gasto com a busca de informações em sistemas não integrados: Ineficiência.", "category": "NVA", "color_code": "Red", "id": "BA389"},
    {"activity": "Processo de lavagem de barris que consome muita energia: Ineficiência energética.", "category": "NVA", "color_code": "Red", "id": "BA390"},
    {"activity": "Descarte de cerveja por sabor de diacetil: Falha na maturação ou levedura.", "category": "NVA", "color_code": "Red", "id": "BA391"},
    {"activity": "Re-fermentação de lotes por contaminação: Necessidade de adicionar nova levedura.", "category": "NVA", "color_code": "Red", "id": "BA392"},
    {"activity": "Uso de mais produtos de limpeza do que o necessário: Desperdício de insumos.", "category": "NVA", "color_code": "Red", "id": "BA393"},
    {"activity": "Tempo de espera por feedback em projetos: Atraso na tomada de decisões.", "category": "NVA", "color_code": "Red", "id": "BA394"},
    {"activity": "Movimentação de matérias-primas para áreas de armazenamento temporário desnecessário.", "category": "NVA", "color_code": "Red", "id": "BA395"},
    {"activity": "Produção de espuma excessiva durante a transferência de cerveja: Perda de produto.", "category": "NVA", "color_code": "Red", "id": "BA396"},
    {"activity": "Armazenamento de produtos acabados em excesso em áreas de alto custo: Otimização de espaço.", "category": "NVA", "color_code": "Red", "id": "BA397"},
    {"activity": "Desperdício de energia por sistemas de refrigeração com vazamentos de gás.", "category": "NVA", "color_code": "Red", "id": "BA398"},
    {"activity": "Atrasos na produção devido a falta de peças de reposição críticas.", "category": "NVA", "color_code": "Red", "id": "BA399"},
    {"activity": "Tempo gasto com a correção de dados de inventário imprecisos: Retrabalho administrativo.", "category": "NVA", "color_code": "Red", "id": "BA400"}
];

export const quizCategoryNames = {
    "AV": "Agrega Valor",
    "NVA-N": "Não Agrega Valor, mas Necessário",
    "NVA": "Não Agrega Valor / Desperdício"
};